name: Update dependencies

on:
  schedule:
    - cron: '13 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2

      - run: yarn up '*'
      - run: yarn ci

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.1.0
        with:
          commit-message: "chore: Update all dependencies"
          branch: automatic_dependency_updates
          title: Update all dependencies
          body: An updated update of all NPM dependencies.
          labels: auto-merge
          #reviewers: # optional
